version: "3.7"
services:

# PSSensio
# ---------------------------------------------
  PSSensio:
    image: 5vein/pssensio
    container_name: PSSensio
    hostname: PSSensio
    environment:
      - TZ=Europe/Oslo
    ports:
      - "80:80"
    restart: unless-stopped
# ---------------------------------------------



# # PSSensio
# # ---------------------------------------------
#   PSSensio:
#     image: 5vein/pssensio
#     container_name: PSSensio
#     hostname: PSSensio
#     environment:
#       - TZ=Europe/Oslo
#     ports:
#       - "80:80"
#     networks:
#       MACVLAN:
#         # Listning on port 80
#         ipv4_address: 192.168.3.194
#     restart: unless-stopped


# # ===============================================
# # docker-compose - Network Settings
# # ===============================================
# networks:
#   MACVLAN:
#     external: true
# # ---------------------------------------------
